### ISSUE TITLE
No Favicon

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/blog.ubports.com#2]
From https://github.com/ubports/ubports.com/issues/11 :

Looking at the blog mainpage ......

I noticed that there was no browser icon - image here - that loads to declare the ubports logo.

Seems quite amateurish at present.

**Comment by annaleaser** [comment]
please add the bounty-tag. [Thankyou](https://www.bountysource.com/issues/41223659-no-favicon).

**Comment by annaleaser** [comment]
please add the bounty-tag. [Thankyou](https://www.bountysource.com/issues/41223659-no-favicon).

**Comment by molikmiah** [comment]
I haved fixed this.

BountySource: https://www.bountysource.com/issues/41223659-no-favicon
Pull Request is here: https://github.com/ubports/blog.ubports.com/pull/3

**Comment by UniversalSuperBox** [comment]
You bet. A few commits later (Apparently Jekyll is smarter than I) and the favicon is good to go.
